const {Builder, By, Key, until} = require('selenium-webdriver');

(async function sections() {
	let driver = new Builder().forBrowser('chrome').build();
	try {
		driver.manage().setTimeouts( {implicit: 5000} );
		driver.get('http://localhost/litecart/admin/login.php');
		
		let loginField = await driver.findElement(By.name('username'));
		await loginField.sendKeys('admin');
		let passwordField = await driver.findElement(By.name('password'));
		await passwordField.sendKeys('admin');
		let submitButton = await driver.findElement(By.xpath('//button[@type="submit"]'));		
		await submitButton.click();
		let appearence = await driver.findElement(By.xpath('//a[@href="http://localhost/litecart/admin/?app=appearance&doc=template"]'));
		await appearence.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000); //проверка на отображение h1 заголовка
		let logotype = await driver.findElement(By.xpath('//a[@href="http://localhost/litecart/admin/?app=appearance&doc=logotype"]'));
		await	logotype.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);
		let catalog = await driver.findElement(By.xpath('//a[@href="http://localhost/litecart/admin/?app=catalog&doc=catalog"]'));
		await catalog.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);
		let productGroups = await driver.findElement(By.linkText('Product Groups'));			
		await productGroups.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let optionGroups = await driver.findElement(By.linkText('Option Groups'));			
		await optionGroups.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);					
		let manufacturers = await driver.findElement(By.linkText('Manufacturers'));			
		await manufacturers.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);				
		let suppliers = await driver.findElement(By.linkText('Suppliers'));			
		await suppliers.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);				
		let deliveryStatuses = await driver.findElement(By.linkText('Delivery Statuses'));			
		await deliveryStatuses.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);						
		let soldOutStatuses = await driver.findElement(By.linkText('Sold Out Statuses'));			
		await soldOutStatuses.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		 		
		let quantityUnits = await driver.findElement(By.linkText('Quantity Units'));			
		await quantityUnits.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);			
		let csvImportExport = await driver.findElement(By.linkText('CSV Import/Export'));			
		await csvImportExport.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);				
		let countries = await driver.findElement(By.linkText('Countries'));			
		await countries.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);			
		let customers = await driver.findElement(By.linkText('Customers'));			
		await customers.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);			
		let customersImportExport = await driver.findElement(By.xpath('//a[@href="http://localhost/litecart/admin/?app=customers&doc=csv"]'));			
		await customersImportExport.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);			
		let newsletter = await driver.findElement(By.linkText('Newsletter'));			
		await newsletter.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let geozones = await driver.findElement(By.linkText('Geo Zones'));			
		await geozones.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let languages = await driver.findElement(By.linkText('Languages'));			
		await languages.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let storageEncoding = await driver.findElement(By.linkText('Storage Encoding'));			
		await storageEncoding.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let modules = await driver.findElement(By.linkText('Modules'));			
		await modules.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);			
		let customer = await driver.findElement(By.xpath('//a[@href="http://localhost/litecart/admin/?app=modules&doc=customer"]'));			
		await customer.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);					
		let shipping = await driver.findElement(By.linkText('Shipping'));			
		await shipping.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let payment = await driver.findElement(By.linkText('Payment'));			
		await payment.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let ordedTotal = await driver.findElement(By.linkText('Order Total'));			
		await ordedTotal.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let ordedSuccess = await driver.findElement(By.linkText('Order Success'));			
		await ordedSuccess.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let ordedAction = await driver.findElement(By.linkText('Order Action'));			
		await ordedAction.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);	
		let orders = await driver.findElement(By.linkText('Orders'));			
		await orders.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let orderStatuses = await driver.findElement(By.linkText('Order Statuses'));			
		await orderStatuses.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);			
		let pages = await driver.findElement(By.linkText('Pages'));	
		await pages.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let reports = await driver.findElement(By.linkText('Reports'));
		await reports.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let mostSoldProducts = await driver.findElement(By.xpath('//a[@href="http://localhost/litecart/admin/?app=reports&doc=most_sold_products"]'));
		await mostSoldProducts.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let settings	= await driver.findElement(By.linkText('Settings'));
		await settings.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let defaults	= await driver.findElement(By.linkText('Defaults'));
		await defaults.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);			
		let general	= await driver.findElement(By.linkText('General'));
		await general.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);			
		let listing	= await driver.findElement(By.linkText('Listings'));
		await listing.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);			
		let images	= await driver.findElement(By.linkText('Images'));
		await images.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);			
		let checkout	= await driver.findElement(By.linkText('Checkout'));
		await checkout.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);			
		let advanced	= await driver.findElement(By.linkText('Advanced'));
		await advanced.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let security	= await driver.findElement(By.linkText('Security'));
		await security.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);			
		let slides	= await driver.findElement(By.linkText('Slides'));
		await slides.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let tax	= await driver.findElement(By.linkText('Tax'));
		await tax.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let taxRates	= await driver.findElement(By.linkText('Tax Rates'));
		await taxRates.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let translations	= await driver.findElement(By.linkText('Translations'));
		await translations.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let scanFiles	= await driver.findElement(By.linkText('Scan Files'));
		await scanFiles.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let translationsImportExport = await driver.findElement(By.xpath('//a[@href="http://localhost/litecart/admin/?app=translations&doc=csv"]'));
		await translationsImportExport.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let users = await driver.findElement(By.linkText('Users'));
		await users.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);		
		let vqmods = await driver.findElement(By.linkText('vQmods'));
		await vqmods.click();
		await driver.wait(until.elementLocated(By.xpath('//h1')), 2000);				
	} finally {
			await driver.quit();
	} 
})();

//driver.wait(until.elementLocated(By.xpath('//a[@href="http://localhost/litecart/admin/?app=catalog&doc=catalog"]'), 3000/*ms*/));